Repository ttmc14/ttmc14, pull requests merged in 2025-09, with the labels that each got.

#70 Rework organic
  Resources/Prototypes/_MC/Entities/Clothing/Eyes/glasses.yml
  Resources/Prototypes/_MC/Entities/Clothing/Eyes/hud.yml
  Resources/Prototypes/_MC/Entities/Objects/Effects/Fire/base.yml
  Resources/Prototypes/_MC/Entities/Objects/Effects/Fire/flamethrower.yml
  Resources/Prototypes/_MC/Entities/Objects/Medical/healing.yml
  Resources/Prototypes/_MC/Reagents/pyrotechnic.yml
  Resources/Prototypes/_MC/Roles/Marines/Command/captain.yml
  Resources/Prototypes/_MC/Roles/Marines/Command/field_commander.yml
  Resources/Prototypes/_MC/Roles/Marines/Command/staff_officer.yml
  Resources/Prototypes/_MC/Roles/Marines/EnR/chief_ship_engineer.yml
  Resources/Prototypes/_MC/Roles/Marines/EnR/requisitions_officer.yml
  Resources/Prototypes/_MC/Roles/Marines/EnR/ship_technician.yml
  Resources/Prototypes/_MC/Roles/Marines/Medical/chief_medical_officer.yml
  Resources/Prototypes/_MC/Roles/Marines/Medical/medical_doctor.yml
  Resources/Prototypes/_MC/Roles/Marines/Medical/researcher.yml
  Resources/Prototypes/_MC/Roles/Marines/Squad/squad_corpsman.yml
  Resources/Prototypes/_MC/Roles/Marines/Squad/squad_engineer.yml
  Resources/Prototypes/_MC/Roles/Marines/Squad/squad_leader.yml
  Resources/Prototypes/_MC/Roles/Marines/Squad/squad_marine.yml
  Resources/Prototypes/_MC/Roles/Marines/Squad/squad_smartgunner.yml
  Resources/Prototypes/_MC/Roles/Marines/VehicleCrew/assault_crewman.yml
  Resources/Prototypes/_MC/Roles/Marines/VehicleCrew/pilot_officer.yml
  Resources/Prototypes/_MC/Roles/Marines/VehicleCrew/transport_officer.yml
  Resources/Prototypes/_RMC14/Entities/Mobs/Species/base.yml
Labels: Changes: No C#

#68 MC Lava and railing
  Resources/Prototypes/_MC/Entities/Structures/Walls/Railing/railing.yml
  Resources/Prototypes/_MC/Entities/Tiles/lava.yml
Labels: Changes: No C#

#92 Stamina [No Parity]
  Content.Server/_MC/Stamina/MCStaminaActiveSystem.cs
  Content.Shared/_MC/Chemistry/Effects/MCStamina.cs
  Content.Shared/_MC/Stamina/MCStaminaActiveComponent.cs
  Content.Shared/_MC/Stamina/MCStaminaComponent.cs
  Content.Shared/_MC/Stamina/MCStaminaDamageOnCollideComponent.cs
  Content.Shared/_MC/Stamina/MCStaminaDamageOnHitComponent.cs
  Content.Shared/_MC/Stamina/MCStaminaSystem.cs
  Resources/Prototypes/_MC/Entities/Objects/Weapons/Guns/Special/pepperball.yml
  Resources/Prototypes/_MC/Reagents/Medicine/tier3.yml
  Resources/Prototypes/_RMC14/Entities/Mobs/Species/base.yml
Labels: size/M

#96 Светильники
  Resources/Maps/_MC/pillar_of_spring.yml
  Resources/Prototypes/_MC/Entities/Structures/Lighting/lighting.yml
Labels: Changes: No C#, Changes: Map, size/M, S: Needs Review, S: Untriaged
